# Generated by Django 5.2.7 on 2025-10-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, editable=False, max_length=15, unique=True)),
                ('tagline', models.CharField(max_length=200)),
                ('password', models.CharField()),
                ('email', models.CharField(db_index=True, unique=True)),
                ('persona_name', models.CharField(choices=[('n', 'Novice'), ('o', 'Otaku'), ('w', 'Weeb')], default='n')),
                ('last_online', models.DateTimeField(auto_now=True)),
                ('pfp', models.CharField()),
                ('banner', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
