# Generated by Django 5.2.7 on 2025-10-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.CharField(db_column='banner'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_column='email', db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(auto_now=True, db_column='last_online'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='persona_name',
            field=models.CharField(choices=[('n', 'Novice'), ('o', 'Otaku'), ('w', 'Weeb')], db_column='persona_name', default='n'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.CharField(db_column='pfp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tagline',
            field=models.CharField(db_column='tagline', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_column='username', db_index=True, editable=False, max_length=15, unique=True),
        ),
    ]
