# Generated by Django 5.2.7 on 2025-10-31 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.TextField(max_length=50, verbose_name='anime_name'),
        ),
        migrations.AlterField(
            model_name='animelist',
            name='name',
            field=models.TextField(max_length=25, verbose_name='ListName'),
        ),
        migrations.AlterField(
            model_name='animelist',
            name='types',
            field=models.TextField(choices=[('C', 'Completed'), ('O', 'Ongoing')], default='O', verbose_name='types'),
        ),
        migrations.AlterField(
            model_name='animelistentry',
            name='status',
            field=models.TextField(choices=[('C', 'Completed'), ('O', 'Ongoing')], max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='banner',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='persona_name',
            field=models.TextField(choices=[('n', 'Novice'), ('o', 'Otaku'), ('w', 'Weeb')], default='n'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pfp',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tagline',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.TextField(db_index=True, editable=False, max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
            ],
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
