# Generated by Django 5.2.7 on 2025-10-29 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_service', '0002_alter_user_banner_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='anime_name')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='persona_name',
            field=models.CharField(choices=[('n', 'Novice'), ('o', 'Otaku'), ('w', 'Weeb')], default='n'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='tagline',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, editable=False, max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='AnimeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='ListName')),
                ('description', models.TextField(verbose_name='description')),
                ('types', models.CharField(choices=[('C', 'Completed'), ('O', 'Ongoing')], default='O', verbose_name='types')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_service.user', verbose_name='created_by')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'Completed'), ('O', 'Ongoing')], max_length=50, verbose_name='status')),
                ('review', models.TextField(null=True, verbose_name='review')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='rating')),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_service.anime', verbose_name='anime_id')),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_service.animelist', verbose_name='list_id')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_service.user', verbose_name='created_by')),
            ],
        ),
    ]
